language: python
install:
  - pip install -r REQUIREMENTS --use-mirrors
  - pip install -r TEST-REQUIREMENTS --use-mirrors
before_script:
  - "python setup.py install"
python:
  - "2.6"
  - "2.7"
  - "3.3"
script: py.test tests/test_*.py
