language: python
install:
  - pip install -r REQUIREMENTS
  - pip install -r TEST-REQUIREMENTS
before_script:
  - "pip install ."
python:
  - "2.7"
  - "3.4"
  - "3.5"
script: py.test tests/test_*.py
